#!/usr/bin/env python3
"""
propulsion_matching.py — parametric ideal-gas nozzle + afterburner heat-balance
model for the Mach 1 RC program (25 R07/R08 evidence).

Python stdlib only. No CAD is regenerated by this tool.

WHAT THIS REPLACES
  Docs 18 sec 2.1 / 21 sec 1 & 6 use the momentum-only shortcut
  gross = mdot * Vj,  ram = mdot * Vinf,  net = gross - ram,
  with Vj = Vj_dry*sqrt(T7/1000) and a static-to-flight mass-flow ratio.
  That assumes (a) equal effective exhaust velocity, (b) negligible pressure
  thrust, (c) a single mdot that is both core air and nozzle flow. None of
  (a)-(c) is established; nozzle velocity depends on pressure ratio, throat
  area, discharge coefficient and total temperature, not T7 alone (25 R07).

  This tool replaces the logical equivalence with a parametric ideal-gas
  convergent-nozzle model:
    * choked mass flow:      mdot = Cd Pt A*/sqrt(Tt) * sqrt(g/R) *
                                   ((g+1)/2)^(-(g+1)/(2(g-1)))
    * critical pressure:     Pt/Pe* = ((g+1)/2)^(g/(g-1))
    * throat sonic speed:    a* = sqrt(g R T*), T* = 2 Tt/(g+1)
    * thrust split:          F = mdot Ve + (Pe-Pa) Ae
    * ram bookkeeping:       net = gross - mdot_air * Vinf
                             (fuel carried onboard adds exit momentum without
                             a ram penalty; the incoming-air momentum deficit
                             is the ram term)
    * heat addition:         constant-cp sensible-enthalpy balance including added fuel

  All gas properties, h, emissivities, discharge coefficient and efficiency are
  EXPLICIT unvalidated parameters. Every number printed below is a
  development/parametric estimate, not a measured result. Baseline mdot = 1.10
  kg/s (18 sec 2.1) is used only as a planning target; nozzle Pt/T7 come from an
  engine map that is NOT available, so closure is not claimed.

Authoritative inputs (cited):
  18 sec 2.1 : mdot_air 1.10 kg/s, T5 ~1000 K, Vj_dry ~566 m/s, net dry ~257 N,
               net wet 450-475 N; ram = 1.10*328 = 361 N
  13:65      : Vinf = 328 m/s at 10 kft ISA; 13:84 Pt/P = 1.893; 13:94-96 corr.
  21 sec 2/3 : AB fuel 27.3 g/s at T7=1800 K, cp=1200, LHV=43 MJ/kg, eta=0.90
  14 sec 1/4 : throats 45 mm dry / 55 mm wet; liner 80 mm ID; CAD ab_liner_step
               has 20 x 1 mm film holes at x=10 mm (the 105-115 target is not
               in CAD, 25 R08)
  17 sec 1c  : film-hole choked-flow constant 2.47e-4 kg/s per 1 mm hole
  17 sec 1e  : annulus h = 125 W/m2K, T_cool_in = 423 K, shell ~610 K
"""

import math

SIGMA = 5.67e-8          # W/m2K4 Stefan-Boltzmann
G_AIR = 1.4
R_AIR = 287.05           # J/kgK
G_PROD = 1.33            # combustion products, cp ~ 1200 -> R ~ 298
R_PROD = 298.0           # J/kgK (cp*(1-1/g))
GAMMA_DEFAULT = G_AIR
R_DEFAULT = R_AIR
PA_10KFT = 69.7e3        # Pa, ISA static at 10 kft (13:61)
VINF_M1 = 328.0          # m/s, a at 10 kft (13:65)
MDOT_AIR_M1 = 1.10       # kg/s corrected-flow planning target (18 sec 2.1)
MDOT_CORE_FUEL = 0.022   # kg/s dry core fuel ~22 g/s at M1 (21 sec 2 note)
MDOT_AB_FUEL_1800 = 0.0273  # kg/s (21 sec 2)
T5_DRY = 1000.0          # K (18 sec 2.1)
T7_NOM = 1800.0          # K design
CP_PROD = 1200.0         # J/kgK (17 sec 1a)
LHV = 43.0e6             # J/kg Jet A1
ETA_COMB = 0.90
VJ_DRY_DOC = 566.0       # m/s (18 sec 2.1, 13:123)
DRY_NET = 257.0          # N (18 sec 2.1)
AREA45 = math.pi / 4.0 * 0.045 ** 2   # m2, dry throat
AREA55 = math.pi / 4.0 * 0.055 ** 2   # m2, wet throat


def critical_pressure_ratio(gamma=GAMMA_DEFAULT):
    """Pt/Pe_sonic for isentropic flow of a perfect gas."""
    _positive(gamma=gamma)
    if gamma <= 1:
        raise ValueError("gamma must exceed 1")
    return ((gamma + 1.0) / 2.0) ** (gamma / (gamma - 1.0))


def _positive(**values):
    for name, value in values.items():
        if not math.isfinite(value) or value <= 0:
            raise ValueError(f"{name} must be finite and positive")


def _nonnegative(**values):
    for name, value in values.items():
        if not math.isfinite(value) or value < 0:
            raise ValueError(f"{name} must be finite and nonnegative")


def _fraction(**values):
    _nonnegative(**values)
    if any(value > 1 for value in values.values()):
        raise ValueError("fractions must be <= 1")


def choked_mass_flow(Pt, Tt, A_eff, gamma=GAMMA_DEFAULT, R=R_DEFAULT):
    """Choked (sonic) throat mass flow, kg/s."""
    _positive(Pt=Pt, Tt=Tt, A_eff=A_eff, R=R)
    critical_pressure_ratio(gamma)
    f = math.sqrt(gamma / R) * ((gamma + 1.0) / 2.0) ** (-(gamma + 1.0) / (2.0 * (gamma - 1.0)))
    return Pt * A_eff / math.sqrt(Tt) * f


def pt_required_for_choked_massflow(mdot, Tt, A_eff, gamma=GAMMA_DEFAULT, R=R_DEFAULT):
    """Total pressure, Pa, needed to pass mdot through area A_eff when choked."""
    _positive(mdot=mdot, Tt=Tt, A_eff=A_eff, R=R)
    critical_pressure_ratio(gamma)
    f = math.sqrt(gamma / R) * ((gamma + 1.0) / 2.0) ** (-(gamma + 1.0) / (2.0 * (gamma - 1.0)))
    return mdot * math.sqrt(Tt) / (A_eff * f)


def throat_sonic_velocity(Tt, gamma=GAMMA_DEFAULT, R=R_DEFAULT):
    """Sonic velocity at the throat of a choked convergent nozzle, m/s."""
    _positive(Tt=Tt, R=R)
    critical_pressure_ratio(gamma)
    Tstar = Tt * 2.0 / (gamma + 1.0)
    return math.sqrt(gamma * R * Tstar), Tstar


def achocked(Tt, gamma=GAMMA_DEFAULT, R=R_DEFAULT):
    return throat_sonic_velocity(Tt, gamma, R)[0]


def nozzle_flow(Pt, Tt, A, Pa, gamma=GAMMA_DEFAULT, R=R_DEFAULT, Cd=1.0, eta=1.0):
    """Ideal-gas convergent nozzle.

    Returns dict(mdot, Ve, Pe, choked, F_momentum, F_pressure, F_gross, note).
    eta is a kinetic-energy efficiency on the exit velocity (Ve,eff = sqrt(eta)*Ve).
    Cd scales the effective throat area for mass flow.
    Momentum thrust uses Cd*A mass flow and the effective exit velocity.
    """
    _positive(Pt=Pt, Tt=Tt, A=A, Pa=Pa, R=R, Cd=Cd, eta=eta)
    _fraction(Cd=Cd, eta=eta)
    if Pt < Pa:
        raise ValueError("Pt < Pa: reverse flow is outside this model")
    crit = critical_pressure_ratio(gamma)
    A_eff = Cd * A
    if Pa <= Pt / crit:
        Pe = Pt / crit
        a_s, Tstar = throat_sonic_velocity(Tt, gamma, R)
        Ve = math.sqrt(eta) * a_s
        mdot = choked_mass_flow(Pt, Tt, A_eff, gamma, R)
        choked = True
    else:
        ratio = Pt / Pa
        M = math.sqrt(2.0 / (gamma - 1.0) * (ratio ** ((gamma - 1.0) / gamma) - 1.0))
        Te = Tt / (1.0 + (gamma - 1.0) / 2.0 * M ** 2)
        ae = math.sqrt(gamma * R * Te)
        Ve = math.sqrt(eta) * M * ae
        rhoe = Pa / (R * Te)
        mdot = Cd * rhoe * M * ae * A
        Pe = Pa
        choked = False
    F_mom = mdot * Ve
    F_p = (Pe - Pa) * A
    return {
        "mdot": mdot, "Ve": Ve, "Pe": Pe, "choked": choked,
        "F_momentum": F_mom, "F_pressure": F_p, "F_gross": F_mom + F_p,
        "A": A, "A_eff": A_eff, "Pa": Pa, "crit_pr": crit,
        "note": "choked" if choked else "unchoked",
    }


def flight_net(res, mdot_air, mdot_core_fuel=0.0, mdot_ab_fuel=0.0, Vinf=VINF_M1):
    """Net flight thrust with separated ram bookkeeping.

    Exit momentum uses the TOTAL mass leaving the aircraft (captured air plus
    onboard core/AB fuel); the pressure term uses the nozzle exit
    area and ambient from ``res``; ram is the incoming-AIR momentum deficit.
    Returns (gross, ram, net, mdot_tot)."""
    _nonnegative(mdot_air=mdot_air, mdot_core_fuel=mdot_core_fuel,
                 mdot_ab_fuel=mdot_ab_fuel, Vinf=Vinf)
    _nonnegative(nozzle_mdot=res["mdot"], Ve=res["Ve"])
    _positive(Pe=res["Pe"], Pa=res["Pa"], A=res["A"])
    mdot_tot = mdot_air + mdot_core_fuel + mdot_ab_fuel
    if not math.isclose(mdot_tot, res["mdot"], rel_tol=1e-8, abs_tol=1e-12):
        raise ValueError("air + core fuel + AB fuel must match nozzle mass flow")
    gross = mdot_tot * res["Ve"] + (res["Pe"] - res["Pa"]) * res["A"]
    return gross, mdot_air * Vinf, gross - mdot_air * Vinf, mdot_tot


def heat_addition(mdot_total, cp, mdot_fuel, LHV, eta, T_up, T_ref=298.15):
    """Approximation: mdot_total is UPSTREAM air+core fuel; AB fuel enters at
    zero sensible enthalpy at T_ref. Constant common cp, no dissociation/loss
    beyond eta. Not an exact reacting-gas temperature prediction."""
    _positive(mdot_total=mdot_total, cp=cp, LHV=LHV, eta=eta, T_up=T_up, T_ref=T_ref)
    _fraction(eta=eta)
    _nonnegative(mdot_fuel=mdot_fuel)
    return T_ref + (mdot_total * cp * (T_up - T_ref) + mdot_fuel * LHV * eta) / ((mdot_total + mdot_fuel) * cp)


def fuel_for_temperature_rise(mdot_total, cp, dT, LHV, eta, T_up=T5_DRY, T_ref=298.15):
    """Inverse of heat_addition on the same upstream mass/enthalpy basis."""
    heat_addition(mdot_total, cp, 0, LHV, eta, T_up, T_ref)
    _nonnegative(dT=dT)
    available = LHV * eta - cp * (T_up + dT - T_ref)
    if available <= 0:
        raise ValueError("target temperature is unreachable on this heat model")
    return mdot_total * cp * dT / available


def liner_wall_balance(hg, Tg, eps_g, hc, Tc, Tsh, eps_c, kw, tw, sigma=SIGMA,
                       lo=None, hi=None, tol=1e-3):
    """Steady 1-D lumped liner: gas side (conv+rad) -> wall conduction ->
    annulus back side (conv+rad to shell). Solves the wall hot-face temperature
    T_wo for ENERGY CONSERVATION (gas-side q == back-side q). Prescribing T_wo
    and hoping q matches is not a solution - this is the equilibrium value.

    Returns dict(T_wo, T_wi, q, q_conv_gas, q_rad_gas, q_conv_back, q_rad_back).
    All h/eps/k are explicit unvalidated parameters.
    """
    _positive(Tg=Tg, Tc=Tc, Tsh=Tsh, kw=kw, tw=tw, sigma=sigma, tol=tol)
    _nonnegative(hg=hg, hc=hc)
    _fraction(eps_g=eps_g, eps_c=eps_c)
    if hg + eps_g == 0 or hc + eps_c == 0:
        raise ValueError("both wall faces require heat transfer")
    # Restrict to this model's hot-gas/cold-reservoir heat-flow direction.
    if Tg < max(Tc, Tsh):
        raise ValueError("gas must be at least as hot as the cooling reservoirs")
    # Find the lower hot-face bound whose conducted cold face is nonnegative.
    lower, upper = min(Tc, Tsh), Tg
    for _ in range(100):
        mid = (lower + upper) / 2
        cold = mid - (hg * (Tg-mid) + eps_g*sigma*(Tg**4-mid**4))*tw/kw
        if cold < min(Tc, Tsh):
            lower = mid
        else:
            upper = mid
    lo = upper if lo is None else lo
    hi = Tg if hi is None else hi
    _positive(lo=lo, hi=hi)
    if lo > hi or lo < upper - 1e-8 or hi > Tg:
        raise ValueError("invalid physical wall bracket")

    def q_gas(Two):
        return hg * (Tg - Two) + eps_g * sigma * (Tg ** 4 - Two ** 4)

    def q_back(Two):
        qi = q_gas(Two)
        Twi = Two - qi * tw / kw
        return hc * (Twi - Tc) + eps_c * sigma * (Twi ** 4 - Tsh ** 4)

    f = lambda Two: q_gas(Two) - q_back(Two)
    if f(lo) * f(hi) > 0:
        return {"converged": False, "note": "no sign change in bracket"}
    for _ in range(200):
        mid = 0.5 * (lo + hi)
        if abs(f(mid)) < tol or (hi - lo) < 1e-6:
            break
        if f(lo) * f(mid) <= 0:
            hi = mid
        else:
            lo = mid
    Two = 0.5 * (lo + hi)
    q = q_gas(Two)
    Twi = Two - q * tw / kw
    return {
        "converged": True, "T_wo": Two, "T_wi": Twi, "q": q,
        "q_conv_gas": hg * (Tg - Two), "q_rad_gas": eps_g * sigma * (Tg ** 4 - Two ** 4),
        "q_conv_back": hc * (Twi - Tc), "q_rad_back": eps_c * sigma * (Twi ** 4 - Tsh ** 4),
    }


def shell_blanket_composite(T_shell, k_b, t_b, h_ext, T_amb, eps_f, sigma=SIGMA):
    """Steady 1-D: blanket conduction from T_shell to composite outer surface,
    then external convection + radiation to ambient. Solves T_composite by
    energy balance (conducted q == rejected q). Banded: returns also the heat
    flux and the residual pass against a 373 K composite-contact limit."""
    _positive(T_shell=T_shell, k_b=k_b, t_b=t_b, T_amb=T_amb, sigma=sigma)
    _nonnegative(h_ext=h_ext)
    _fraction(eps_f=eps_f)
    if T_shell < T_amb:
        raise ValueError("T_shell must be >= ambient for this heating model")
    lo = T_amb
    hi = T_shell

    def q_cond(Tc):
        return (k_b / t_b) * (T_shell - Tc)

    def q_ext(Tc):
        return h_ext * (Tc - T_amb) + eps_f * sigma * (Tc ** 4 - T_amb ** 4)

    f = lambda Tc: q_cond(Tc) - q_ext(Tc)
    if f(lo) * f(hi) > 0:
        return {"converged": False, "note": "no sign change"}
    for _ in range(200):
        mid = 0.5 * (lo + hi)
        if abs(f(mid)) < 1e-2 or (hi - lo) < 1e-5:
            break
        if f(lo) * f(mid) <= 0:
            hi = mid
        else:
            lo = mid
    Tc = 0.5 * (lo + hi)
    q = q_cond(Tc)
    return {
        "converged": True, "T_composite": Tc,
        "q": q, "pass_100C": Tc < 373.15,
        "q_cond": q, "q_ext": q_ext(Tc),
    }


def _fmt_bar(p):
    return p / 1.0e5


def main():
    print("=" * 78)
    print("PROPULSION MATCHING + HOT-SECTION THERMAL — DEVELOPMENT MODEL (25 R07/R08)")
    print("Stdlib only. All gas/h/mu/eps/Cd/eta are explicit unvalidated parameters.")
    print("Baseline mdot 1.10 kg/s is a PLANNING TARGET; Pt/T7 engine map is missing,")
    print("so closure is NOT claimed. See 32_propulsion_thermal.md.")
    print("=" * 78)

    # --- 1. Gas-dynamics sanity: critical pressure and choked-flow textbook limits
    print("\n[S1] TEXTBOOK LIMITS")
    for gamma, R, name in ((G_AIR, R_AIR, "air g=1.40"), (G_PROD, R_PROD, "prod g=1.33")):
        print(f"  {name:14s}: crit. pressure ratio Pt/Pe* = {critical_pressure_ratio(gamma):6.3f} "
              f"(air textbook 1.893);  a*/sqrt(Tt) = {achocked(1.0, gamma, R):6.2f} m/s/sqrt(K)")

    # --- 2. Throat feasibility: Pt required to pass design flow at 45/55 mm
    print("\n[S2] NOZZLE-REQUIRED TOTAL PRESSURE FOR 45/55 mm THROATS (choked, Cd=1)")
    print("  dry : 45 mm throat, Tt = T5 = 1000 K, mdot = air + core fuel = 1.122 kg/s")
    print("  wet : 55 mm throat, Tt = T7,    mdot = 1.10 + 0.022 + 0.0273 = 1.149 kg/s")
    for name, A, Tt, mdot, gamma, R in (
        ("dry 45mm T5=1000K", AREA45, T5_DRY, MDOT_AIR_M1 + MDOT_CORE_FUEL, G_AIR, R_AIR),
        ("wet 55mm 1700K   ", AREA55, 1700.0, MDOT_AIR_M1 + MDOT_CORE_FUEL + MDOT_AB_FUEL_1800, G_PROD, R_PROD),
        ("wet 55mm 1800K   ", AREA55, 1800.0, MDOT_AIR_M1 + MDOT_CORE_FUEL + MDOT_AB_FUEL_1800, G_PROD, R_PROD),
        ("wet 55mm 1900K   ", AREA55, 1900.0, MDOT_AIR_M1 + MDOT_CORE_FUEL + MDOT_AB_FUEL_1800, G_PROD, R_PROD),
    ):
        Pt = pt_required_for_choked_massflow(mdot, Tt, A, gamma, R)
        pcrit = critical_pressure_ratio(gamma)
        print(f"  {name}: needs Pt = {Pt/1e5:6.2f} bar abs (crit.-flow only; "
              f"integration loss/Cd would raise it). Critical Pt vs 10 kft ambient "
              f"= {pctrl_pa(pcrit):.2f} bar (press. ratio {pcrit:.2f}).")

    # --- 3. Mass bookkeeping inconsistency in doc 18/21 (R07)
    print("\n[S3] RAM/FUEL BOOKKEEPING (18 sec 2.1 uses mdot=1.10 for BOTH gross and ram)")
    mdot_tot = MDOT_AIR_M1 + MDOT_CORE_FUEL + MDOT_AB_FUEL_1800
    print(f"  Interpretation A (air=1.10, all fuel exits): nozzle mass = {mdot_tot:.3f} kg/s")
    print(f"  Interpretation B (single mdot=1.10 incl. fuel): nozzle mass = 1.100 kg/s")
    Vj = VJ_DRY_DOC * math.sqrt(T7_NOM / 1000.0)
    grossA, grossB = mdot_tot * Vj, 1.10 * Vj
    print(f"  gross(A) = {grossA:6.1f} N  vs gross(B) = {grossB:6.1f} N "
          f"-> net differs by {grossA - grossB:+.1f} N at the same 361 N ram "
          f"(~{(grossA-grossB)/450*100:.0f}% of the 450 N contract).")
    print(f"  Also: the quoted ram 361 N = 1.10*328 uses AIR; if 1.10 already "
          f"included fuel the air flow is only ~1.05 -> ram actually ~345 N.")
    # dry Pt needed check with the "566 m/s dry" velocity coefficient
    a_star, _ = throat_sonic_velocity(T5_DRY, G_AIR, R_AIR)
    print(f"  Dry velocity consistency: choked a* at T5=1000 K = {a_star:.1f} m/s; "
          f"doc Vj_dry=566 implies velocity coeff sqrt(eta)={VJ_DRY_DOC/a_star:.3f} "
          f"(eta={ (VJ_DRY_DOC/a_star)**2:.3f}).")

    # --- 4. What the existing 55 mm throat actually passes at guessed Pt (R07)
    print("\n[S4] 55 mm WET THROAT @ T7=1800 K: mass flow vs Pt at 10 kft ambient")
    print("  Pt is NOT in the engine map; swept to show the matching requirement.")
    print("  No inlet spillage or coupled engine/combustion map is solved here;")
    print("  rows are hypothetical nozzle states, not matched engine operating points.")
    print("  Ram uses nozzle flow minus assumed core+AB fuel (0.0493 kg/s).")
    print(f"  {'Pt bar':>7} {'choked':>7} {'mdot kg/s':>10} {'Ve m/s':>8} "
          f"{'F_mom N':>8} {'(Pe-Pa)A N':>10} {'Fgross N':>9} {'net N':>7}")
    for bar in (1.0, 1.5, 2.0, 2.5, 3.0, 4.0, 5.0, 5.27):
        res = nozzle_flow(bar * 1.0e5, T7_NOM, AREA55, PA_10KFT, G_PROD, R_PROD)
        air = res["mdot"] - MDOT_CORE_FUEL - MDOT_AB_FUEL_1800
        _, _, net, _ = flight_net(res, air, MDOT_CORE_FUEL, MDOT_AB_FUEL_1800)
        print(f"  {bar:7.2f} {str(res['choked']):>7} {res['mdot']:10.3f} {res['Ve']:8.1f} "
              f"{res['F_momentum']:8.1f} {res['F_pressure']:10.1f} {res['F_gross']:9.1f} "
              f"{net:7.1f}")

    # --- 5. Heat addition balance (21 sec 2) reproduced from the module
    print("\n[S5] AFTERBURNER HEAT ADDITION")
    mf = fuel_for_temperature_rise(MDOT_AIR_M1 + MDOT_CORE_FUEL, CP_PROD,
                                   T7_NOM - T5_DRY, LHV, ETA_COMB)
    T7 = heat_addition(MDOT_AIR_M1 + MDOT_CORE_FUEL, CP_PROD, mf, LHV, ETA_COMB, T5_DRY)
    print(f"  fuel for 1000->1800 K at mdot_tot: {mf*1000:.2f} g/s (doc 27.3 g/s)")
    print(f"  Constant-cp approximation round trip: fuel {mf*1000:.1f} g/s -> T7 = {T7:.1f} K "
          f"(|err| {abs(T7-T7_NOM):.3f} K)")

    # --- 6. Thermal: prescribing the endpoint T_wo is not a solution (R08)
    print("\n[S6] LINER WALL — WHY PRESCRIBING ENDPOINT TEMPERATURES FAILS")
    print("  17 sec 1d assumes T_wo=1150 K and demands back-side h_c=511 W/m2K")
    print("  at T_c=423 K; the annulus estimate is only h_ann=125 W/m2K.")
    for Tc in (423.0, 516.0):
        r = liner_wall_balance(hg=579.0, Tg=1800.0, eps_g=0.25,
                               hc=125.0, Tc=Tc, Tsh=610.0, eps_c=0.3,
                               kw=18.0, tw=0.001)
        if r["converged"]:
            print(f"  annulus h=125, T_c=(in/avg) {Tc:.0f} K: T_wo = {r['T_wo']:.0f} K, "
                  f"T_wi = {r['T_wi']:.0f} K, q = {r['q']/1e3:.0f} kW/m2")
    # coolant capacity check at claimed q: Q vs mdot*cp*dT
    m_cool, cp_cool = 0.0253, 1000.0
    T_in, T_out_claimed = 423.0, 610.0
    Q_avail = m_cool * cp_cool * (T_out_claimed - T_in)
    A_liner = math.pi * 0.080 * 0.20
    q_claimed, T_wo_claimed, T_wi_claimed = 382e3, 1150.0, 1171.0
    Q_claimed = q_claimed * A_liner
    print(f"  coolant Q available (m={m_cool} kg/s, cp={cp_cool}, 423->610 K) = "
          f"{Q_avail:.0f} W vs claimed liner load {Q_claimed:.0f} W "
          f"({'OK' if Q_avail >= Q_claimed else 'DEFICIT'}).")
    print("  -> a consistent T_wo must satisfy BOTH the wall resistance chain AND")
    print("     coolant energy balance; 17's 382 kW/m2 @ T_wo=1150 K is not that state.")

    # --- 7. Shell -> blanket -> composite (R08)
    print("\n[S7] SHELL TO FUSELAGE: 5 mm blanket (k=0.05) with claimed shell 610 K")
    print(f"  {'h_ext':>6} {'eps_f':>6} {'T_composite K':>13} {'q kW/m2':>8} {'<100C?':>7}")
    for h_ext in (5.0, 10.0, 15.0, 25.0):
        for eps_f in (0.15, 0.9):
            s = shell_blanket_composite(610.0, k_b=0.05, t_b=0.005,
                                        h_ext=h_ext, T_amb=268.0, eps_f=eps_f)
            if s["converged"]:
                print(f"  {h_ext:6.1f} {eps_f:6.2f} {s['T_composite']:13.1f} "
                      f"{s['q']/1e3:8.1f} {str(s['pass_100C']):>7}")
    print("  -> conditional steady surface equilibria only, not material qualification.")
    print("     No external cooling => surface approaches prescribed shell temperature.")

    print("\nDONE: development/parametric only. No closure, no simulated 'hot run'.")

def pctrl_pa(pr):
    return pr * PA_10KFT / 1e5


if __name__ == "__main__":
    main()
